### ISSUE TITLE
Local Navigation [Propose]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-site#4]
## Description

A sticky local navigation for page content displayed within the right rail of an article or documentation page.

### Must Have

- Displays level 2 headings of current page OR tab within page
- Displays level 3 headings of current page OR tab within page (optional)
- Applies `small`/`very small` variant combination of list group (for levels 2, 3)
- Included or excluded via template property. Excluded by default.

## Should Have

- Active section scrolled to marked as selected

### Could Have

- Sticks to top of browser window upon scroll

### Nice to have

- Solves for local navigation height exceeds browser window height

### Out of scope

- Reponsiveness

**Comment by nathanacurtis** [comment]
@jamesmelzer @kevinmpowell Ready for review

**Comment by jamesmelzer** [comment]
@nathanacurtis 

ESDS-site layouts suggest [something] happens on small viewports. What's the responsive behavior for this component?

**Comment by nathanacurtis** [comment]
@jamesmelzer I've documented that this component, for MVP, would be hidden at small viewports.

**Comment by kevinmpowell** [comment]
@nathanacurtis I presume the "active section" would be highlighted as the user scrolls the page vertically?

✅ **Approved with comment**

**Comment by nathanacurtis** [comment]
@kevinmpowell Yes, I've marked active section highlight as a Should.

Closing Propose.
