### ISSUE TITLE
Both Normal and Bold Weights Seem Heavier in Browser

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-site#40]
![image](https://user-images.githubusercontent.com/1165904/98369944-c3657c00-2007-11eb-8367-aee01dfb706c.png)

Should we downgrade both weights by one stop in browser?

**Comment by kevinmpowell** [comment]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/979463/98403557-c6279780-202e-11eb-9c7d-aab2416b4bf1.png">

Shall I update the font weight tokens to be 300/500?

**Comment by nathanacurtis** [comment]
Weird, your 400/600 looks lighter than mine. Let's switch anyway.
